/**
 * The shapes the Rust core sends over IPC.
 *
 * These mirror `src-tauri/src/model.rs` and `src-tauri/src/commands/mod.rs`.
 * Nothing here is invented by the frontend: if a field is not in this file,
 * the interface has no business displaying it.
 */

export type Category =
  | 'ghosts'
  | 'screenshots'
  | 'installers'
  | 'heavy_strays'
  | 'copies'
  | 'caches'
  | 'developer_debris'
  | 'oddments'

export type Confidence = 'low' | 'medium' | 'high'

/** Orthogonal to confidence: what it would cost if Scuttle were wrong. */
export type Risk = 'low' | 'moderate' | 'high' | 'protected'

export type RecommendedAction = 'quarantine' | 'review' | 'inspect_only'

export type TargetKind = 'file' | 'directory'

/** The structured observation behind a piece of evidence. */
export interface EvidenceKind {
  kind: string
  [field: string]: unknown
}

export interface Evidence {
  kind: EvidenceKind
  /** The sentence, generated by the core. The UI renders it, never writes it. */
  summary: string
  weight: number
  /** True when this argues against acting. Shown, not hidden. */
  negative: boolean
  risk_floor: Risk | null
}

export interface GroupMember {
  path: string
  size: number
  modified_unix: number | null
  suggested_keep: boolean
}

export interface StateFingerprint {
  size: number
  modified_unix: number | null
  is_dir: boolean
  child_count: number | null
}

export interface Candidate {
  id: string
  detector: string
  category: Category
  target_kind: TargetKind
  path: string
  display_name: string
  associated_app: string | null
  /**
   * What acting on this would free. For a group that is every redundant
   * member — five identical files report four of them, not one and not five.
   */
  size: number
  /** The whole footprint, including the copy a group keeps. */
  group_bytes: number
  confidence: Confidence
  risk: Risk
  recommended_action: RecommendedAction
  evidence: Evidence[]
  /** One restrained line of Scuttle, derived from the same evidence. */
  remark: string | null
  modified_unix: number | null
  accessed_unix: number | null
  created_unix: number | null
  group: GroupMember[]
  fingerprint: StateFingerprint
}

export interface Pile {
  category: Category
  title: string
  bytes: number
  count: number
  actionable: number
  /** How many Scuttle will sweep unprompted, and what that is worth. */
  confident_count: number
  confident_bytes: number
  items: Candidate[]
}

export interface HiccupSummary {
  permission_denied: number
  vanished: number
  unreadable: number
  loops_avoided: number
}

export interface Findings {
  scan_id: string | null
  finished_unix: number | null
  piles: Pile[]
  total_bytes: number
  reclaimable_bytes: number
  files_seen: number
  hiccups: HiccupSummary
  has_rummaged: boolean
}

export type Phase =
  | { phase: 'preparing' }
  | { phase: 'rummaging'; area: string }
  | { phase: 'examining'; note: string }
  | { phase: 'considering'; note: string }
  | { phase: 'finished' }

export interface Progress {
  files_seen: number
  bytes_seen: number
  candidates_found: number
  current_area: string
}

export interface ScanSummary {
  scan_id: string
  files_seen: number
  bytes_seen: number
  candidates_found: number
  reclaimable_bytes: number
  duration_ms: number
  cancelled: boolean
  hiccups: HiccupSummary
}

export interface RootDescription {
  label: string
  path: string
}

export interface RummageStarted {
  scan_id: string
  roots: RootDescription[]
}

export type QuarantineStatus = 'held' | 'restored' | 'removed'

export interface QuarantineRecord {
  id: string
  finding_id: string | null
  original_path: string
  stored_path: string
  display_name: string
  category: Category
  size: number
  content_hash: string | null
  evidence: Evidence[]
  quarantined_unix: number
  expires_unix: number
  status: QuarantineStatus
  resolved_unix: number | null
}

export interface QuarantineView {
  items: QuarantineRecord[]
  held_bytes: number
  retention_days: number
}

export type KeepChoice = 'newest' | 'oldest'

export interface GroupRefusal {
  display_name: string
  reason: string
  code: ScuttleError['code']
}

export interface GroupOutcome {
  held: QuarantineRecord[]
  kept: string
  /** Members Scuttle would not move. Partial success is the normal case. */
  refused: GroupRefusal[]
}

export interface BulkOutcome {
  held: QuarantineRecord[]
  bytes: number
  /** Findings Scuttle would not move. Partial success is normal. */
  refused: GroupRefusal[]
}

/**
 * What emptying the drawer managed to do. `bytes` counts only items that were
 * really removed, because this is the one number in Scuttle that claims space
 * actually came back.
 */
export interface PurgeOutcome {
  removed: number
  bytes: number
  failed: { display_name: string; reason: string }[]
}

export interface RestoreOutcome {
  path: string
  /** True when the original location was occupied and a new name was used. */
  renamed: boolean
}

export interface SpaceArea {
  label: string
  bytes: number
  /** False when the measurement was truncated: say "at least", not a number. */
  complete: boolean
}

export interface CategoryTally {
  category: Category
  label: string
  bytes: number
  count: number
}

export interface SpaceOverview {
  volume_total: number
  volume_free: number
  volume_used: number
  areas: SpaceArea[]
  worth_checking: CategoryTally[]
  reclaimable_estimate: number
  has_findings: boolean
  summary: string
}

export interface Settings {
  scan_roots: string[]
  include_developer_debris: boolean
  quarantine_retention_days: number
  heavy_threshold: number
  appearance: 'system' | 'light' | 'dark'
  reduced_motion: boolean | null
  has_rummaged_before: boolean
}

export interface HistoryEntry {
  id: string
  action: string
  display_name: string
  category: Category
  size: number
  at_unix: number
  outcome: string
}

export interface DryRunRow {
  detector: string
  category: Category
  path: string
  display_name: string
  size: number
  size_human: string
  confidence: Confidence
  risk: Risk
  action: RecommendedAction
  evidence: string[]
  negative_evidence: string[]
}

export interface DryRunReport {
  roots: string[]
  developer_debris: boolean
  files_seen: number
  duration_ms: number
  would_quarantine: DryRunRow[]
  would_review: DryRunRow[]
  would_surface: DryRunRow[]
  detectors_run: string[]
  notes: string[]
}

/** Errors arrive as a tagged object, never as a stringified Rust type. */
export interface ScuttleError {
  code:
    | 'storage'
    | 'io'
    | 'serde'
    | 'not_found'
    | 'stale'
    | 'refused'
    | 'scan_busy'
    | 'internal'
  message: string
}

export function isScuttleError(value: unknown): value is ScuttleError {
  return (
    typeof value === 'object' &&
    value !== null &&
    'code' in value &&
    'message' in value
  )
}
