/**
 * The shapes the Rust core sends over IPC.
 *
 * These mirror `src-tauri/src/model.rs` and `src-tauri/src/commands/mod.rs`.
 * Nothing here is invented by the frontend: if a field is not in this file,
 * the interface has no business displaying it.
 */

export type Category =
  | 'ghosts'
  | 'screenshots'
  | 'installers'
  | 'heavy_strays'
  | 'copies'
  | 'caches'
  | 'developer_debris'
  | 'oddments'

export type Confidence = 'low' | 'medium' | 'high'

/** Orthogonal to confidence: what it would cost if Scuttle were wrong. */
export type Risk = 'low' | 'moderate' | 'high' | 'protected'

export type RecommendedAction = 'quarantine' | 'review' | 'inspect_only'

export type TargetKind = 'file' | 'directory'

/** The structured observation behind a piece of evidence. */
export interface EvidenceKind {
  kind: string
  [field: string]: unknown
}

export interface Evidence {
  kind: EvidenceKind
  /** The sentence, generated by the core. The UI renders it, never writes it. */
  summary: string
  weight: number
  /** True when this argues against acting. Shown, not hidden. */
  negative: boolean
  risk_floor: Risk | null
}

export interface GroupMember {
  path: string
  size: number
  modified_unix: number | null
  suggested_keep: boolean
}

export interface StateFingerprint {
  size: number
  modified_unix: number | null
  is_dir: boolean
  child_count: number | null
}

export interface Candidate {
  id: string
  detector: string
  category: Category
  target_kind: TargetKind
  path: string
  display_name: string
  associated_app: string | null
  /**
   * What acting on this would free. For a group that is every redundant
   * member — five identical files report four of them, not one and not five.
   */
  size: number
  /** The whole footprint, including the copy a group keeps. */
  group_bytes: number
  confidence: Confidence
  risk: Risk
  recommended_action: RecommendedAction
  evidence: Evidence[]
  /** One restrained line of Scuttle, derived from the same evidence. */
  remark: string | null
  modified_unix: number | null
  accessed_unix: number | null
  created_unix: number | null
  group: GroupMember[]
  fingerprint: StateFingerprint
}

export interface Pile {
  category: Category
  title: string
  bytes: number
  count: number
  actionable: number
  /** How many Scuttle will sweep unprompted, and what that is worth. */
  confident_count: number
  confident_bytes: number
  items: Candidate[]
}

export interface HiccupSummary {
  permission_denied: number
  vanished: number
  unreadable: number
  loops_avoided: number
}

export interface Findings {
  scan_id: string | null
  finished_unix: number | null
  piles: Pile[]
  total_bytes: number
  reclaimable_bytes: number
  files_seen: number
  hiccups: HiccupSummary
  has_rummaged: boolean
  kind: ScanKind
  /** Whether the scan that produced these was stopped before it finished. */
  cancelled: boolean
}

export type Phase =
  | { phase: 'preparing' }
  | { phase: 'rummaging'; area: string }
  | { phase: 'examining'; note: string }
  | { phase: 'considering'; note: string }
  | { phase: 'finished' }

export interface Progress {
  files_seen: number
  bytes_seen: number
  candidates_found: number
  current_area: string
}

export interface ScanSummary {
  scan_id: string
  files_seen: number
  bytes_seen: number
  candidates_found: number
  reclaimable_bytes: number
  duration_ms: number
  cancelled: boolean
  hiccups: HiccupSummary
}

export interface RootDescription {
  label: string
  path: string
}

export interface RummageStarted {
  scan_id: string
  roots: RootDescription[]
}

export type QuarantineStatus = 'held' | 'restored' | 'removed' | 'moving' | 'restoring' | 'abandoned'

export interface QuarantineRecord {
  id: string
  finding_id: string | null
  original_path: string
  stored_path: string
  display_name: string
  category: Category
  size: number
  content_hash: string | null
  evidence: Evidence[]
  quarantined_unix: number
  expires_unix: number
  status: QuarantineStatus
  resolved_unix: number | null
  /** `contents`: the reviewed files of a shared folder, not the folder. */
  mode?: 'whole' | 'contents'
  /** Files held. One for a whole item. */
  item_count?: number
  /** An interrupted move left something Scuttle would not settle on its own. */
  attention?: boolean
}

export interface QuarantineView {
  items: QuarantineRecord[]
  held_bytes: number
  retention_days: number
}

export type KeepChoice = 'newest' | 'oldest'

export interface GroupRefusal {
  display_name: string
  reason: string
  code: ScuttleError['code']
}

export interface GroupOutcome {
  held: QuarantineRecord[]
  kept: string
  /** Members Scuttle would not move. Partial success is the normal case. */
  refused: GroupRefusal[]
}

export interface BulkOutcome {
  held: QuarantineRecord[]
  bytes: number
  /** Findings Scuttle would not move. Partial success is normal. */
  refused: GroupRefusal[]
}

/**
 * What emptying the drawer managed to do. `bytes` counts only items that were
 * really removed, because this is the one number in Scuttle that claims space
 * actually came back.
 */
export interface PurgeOutcome {
  removed: number
  bytes: number
  failed: { display_name: string; reason: string }[]
}

export interface RestoreOutcome {
  path: string
  /** True when the original location was occupied and a new name was used. */
  renamed: boolean
  /** Files put back. One for a whole item. */
  restored: number
  /** Files that could not be put back and are still in the drawer. */
  remaining: number
  failed: IssueGroup[]
}

// ---- moving into the drawer ------------------------------------------------

/** What went wrong, in terms of what a person could do about it. */
export type FailureKind =
  | 'stale'
  | 'replaced'
  | 'access_denied'
  | 'in_use'
  | 'missing'
  | 'collision'
  | 'no_space'
  | 'read_only'
  | 'path_too_long'
  | 'cross_volume_refused'
  | 'unsupported'
  | 'unsafe'
  | 'cancelled'
  | 'other'

export type NextStep = 'refresh' | 'retry' | 'free_space' | 'leave_alone' | 'close_app'

export type FailurePhase =
  | 'check'
  | 'snapshot'
  | 'prepare'
  | 'publish'
  | 'copy'
  | 'verify'
  | 'remove_source'
  | 'record'
  | 'restore'

/** One kind of failure, counted. Only file *names* are ever carried. */
export interface IssueGroup {
  kind: FailureKind
  phase: FailurePhase
  /** The code the operating system gave, kept exactly. */
  os_code: number | null
  count: number
  samples: string[]
  next_step: NextStep
  explanation: string
}

export type MovePhase =
  | 'checking'
  | 'moving'
  | 'finalizing'
  | 'completed'
  | 'partial'
  | 'failed'
  | 'cancelled'

export type FindingStatus = 'moved' | 'partial' | 'skipped' | 'failed'

export interface FindingResult {
  finding_id: string
  display_name: string
  category: Category | null
  /** What the counts are counts of: a folder's files, or one whole thing. */
  unit: 'files' | 'item'
  status: FindingStatus
  moved: number
  skipped: number
  failed: number
  moved_bytes: number
  record_id: string | null
  needs_refresh: boolean
  retryable: boolean
  issues: IssueGroup[]
  refusal: { code: string; message: string } | null
}

export interface MoveReport {
  outcome: MovePhase
  moved_files: number
  /** Bytes now in the drawer. Moved, not freed. */
  moved_bytes: number
  skipped: number
  failed: number
  remaining: number
  cancelled: boolean
  kept: string | null
  findings: FindingResult[]
  notice: string | null
}

/** One moment in a move. `job_id` and `rev` only ever rise. */
export interface MoveSnapshot {
  job_id: number
  rev: number
  phase: MovePhase
  cancelling: boolean
  /** Unknown (null) until Scuttle has finished checking. */
  total: number | null
  processed: number
  moved: number
  skipped: number
  failed: number
  moved_bytes: number
  /** Bytes actually copied across a drive. Zero for a rename. */
  copied_bytes: number
  label: string
  report: MoveReport | null
}

export type MoveRequest =
  | { kind: 'selection'; ids: string[]; retry?: boolean }
  | { kind: 'confident'; category?: Category | null }
  | { kind: 'group'; id: string; keep: KeepChoice }
  | { kind: 'member'; id: string; member_index: number }

export interface SpaceArea {
  label: string
  bytes: number
  /** False when the measurement was truncated: say "at least", not a number. */
  complete: boolean
}

export interface CategoryTally {
  category: Category
  label: string
  bytes: number
  count: number
}

export interface SpaceOverview {
  volume_total: number
  volume_free: number
  volume_used: number
  areas: SpaceArea[]
  worth_checking: CategoryTally[]
  reclaimable_estimate: number
  has_findings: boolean
  summary: string
}

/** Something Scuttle has been told to leave alone. Never a file operation. */
export interface IgnoredEntry {
  kind: 'path' | 'app' | 'category'
  /** The stored value, used to find the row again. */
  value: string
  /** What to show a person. */
  label: string
}

export interface Settings {
  scan_roots: string[]
  include_developer_debris: boolean
  quarantine_retention_days: number
  heavy_threshold: number
  appearance: 'system' | 'light' | 'dark'
  reduced_motion: boolean | null
  has_rummaged_before: boolean

  /**
   * Staying in the menu bar or system tray.
   *
   * These three depend on each other in order, and the backend enforces that
   * rather than trusting this side: a check cannot happen if closing the
   * window quits, and there is nothing to notify about if no checks happen.
   * `save_settings` returns the settings it actually stored, so the interface
   * shows what is true rather than what was asked for.
   */
  background_mode: boolean
  background_checks: boolean
  background_notify: boolean
  /** A mirror. The truth is whatever the operating system reports. */
  launch_at_login: boolean
  background_intro_seen: boolean
}

/**
 * Which kind of scan produced a set of findings.
 *
 * A background check reads no file contents, so it cannot find duplicates or
 * near-identical screenshots. The findings screen says so, because otherwise
 * their absence reads as "you have none".
 */
export type ScanKind = 'full' | 'glance'

/** Where background mode stands, including the parts the system refused. */
export interface BackgroundStatus {
  /**
   * Whether the tray icon actually exists. When this is false the setting may
   * be on and yet closing the window still quits — and the interface says so
   * rather than letting the setting read as a promise.
   */
  tray_alive: boolean
  mode: boolean
  checks: boolean
  notify: boolean
  /** `null` when the system has not been asked. */
  notifications_permitted: boolean | null
  launch_at_login: boolean
  launch_at_login_available: boolean
  last_check_unix: number
  paused_until_unix: number
  /**
   * The core's own clock. The interface compares against this rather than
   * calling `Date.now()`, so what it says is a pure function of what it was
   * given and the two sides can never disagree about whether a pause is over.
   */
  now_unix: number
  /** A background check the user has not looked at yet. */
  pending_review: string | null
  /** Why nothing is happening at the moment, phrased for a person. */
  waiting_because: string
}

export interface HistoryEntry {
  id: string
  action: string
  display_name: string
  category: Category
  size: number
  at_unix: number
  outcome: string
}

export interface DryRunRow {
  detector: string
  category: Category
  path: string
  display_name: string
  size: number
  size_human: string
  confidence: Confidence
  risk: Risk
  action: RecommendedAction
  evidence: string[]
  negative_evidence: string[]
}

export interface DryRunReport {
  roots: string[]
  developer_debris: boolean
  files_seen: number
  duration_ms: number
  would_quarantine: DryRunRow[]
  would_review: DryRunRow[]
  would_surface: DryRunRow[]
  detectors_run: string[]
  notes: string[]
}

/** Errors arrive as a tagged object, never as a stringified Rust type. */
export interface ScuttleError {
  code:
    | 'storage'
    | 'io'
    | 'serde'
    | 'not_found'
    | 'stale'
    | 'refused'
    | 'scan_busy'
    | 'busy'
    | 'transfer'
    | 'internal'
  message: string
  /** For `transfer`: what kind, in which phase, with which OS code. */
  failure?: {
    kind: FailureKind
    phase: FailurePhase
    os_code: number | null
    item: string
  }
}

export function isScuttleError(value: unknown): value is ScuttleError {
  return (
    typeof value === 'object' &&
    value !== null &&
    'code' in value &&
    'message' in value
  )
}
